// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var PeersInput = exports.PeersInput = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var PeersOutput = exports.PeersOutput = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

var Mutable = exports.Mutable = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

definePeersInput()
definePeersOutput()
defineMutable()

function definePeersInput () {
  PeersInput.encodingLength = encodingLength
  PeersInput.encode = encode
  PeersInput.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.port)) {
      var len = encodings.varint.encodingLength(obj.port)
      length += 1 + len
    }
    if (defined(obj.localAddress)) {
      var len = encodings.bytes.encodingLength(obj.localAddress)
      length += 1 + len
    }
    if (defined(obj.unannounce)) {
      var len = encodings.bool.encodingLength(obj.unannounce)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.port)) {
      buf[offset++] = 8
      encodings.varint.encode(obj.port, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.localAddress)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.localAddress, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.unannounce)) {
      buf[offset++] = 24
      encodings.bool.encode(obj.unannounce, buf, offset)
      offset += encodings.bool.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      port: 0,
      localAddress: null,
      unannounce: false
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.port = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 2:
        obj.localAddress = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.unannounce = encodings.bool.decode(buf, offset)
        offset += encodings.bool.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function definePeersOutput () {
  PeersOutput.encodingLength = encodingLength
  PeersOutput.encode = encode
  PeersOutput.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.peers)) {
      var len = encodings.bytes.encodingLength(obj.peers)
      length += 1 + len
    }
    if (defined(obj.localPeers)) {
      var len = encodings.bytes.encodingLength(obj.localPeers)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.peers)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.peers, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.localPeers)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.localPeers, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      peers: null,
      localPeers: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.peers = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.localPeers = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defineMutable () {
  Mutable.encodingLength = encodingLength
  Mutable.encode = encode
  Mutable.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.value)) {
      var len = encodings.bytes.encodingLength(obj.value)
      length += 1 + len
    }
    if (defined(obj.signature)) {
      var len = encodings.bytes.encodingLength(obj.signature)
      length += 1 + len
    }
    if (defined(obj.seq)) {
      var len = encodings.varint.encodingLength(obj.seq)
      length += 1 + len
    }
    if (defined(obj.salt)) {
      var len = encodings.bytes.encodingLength(obj.salt)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.value)) {
      buf[offset++] = 10
      encodings.bytes.encode(obj.value, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.signature)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.signature, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.seq)) {
      buf[offset++] = 24
      encodings.varint.encode(obj.seq, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.salt)) {
      buf[offset++] = 34
      encodings.bytes.encode(obj.salt, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      value: null,
      signature: null,
      seq: 0,
      salt: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.value = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 2:
        obj.signature = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.seq = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 4:
        obj.salt = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
